phrases = [
    "The quick brown fox jumps over the lazy dog.",
    "Python is a high-level programming language.",
    "Coding is like solving puzzles with logic.",
    "Practice makes perfect in typing skills.",
    "Efficiency is doing things right; effectiveness is doing the right things.",
    "Happiness is not something ready-made. It comes from your own actions.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "In the middle of difficulty lies opportunity.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "Believe you can and you're halfway there.",
    "Be the change that you wish to see in the world.",
    "Don't watch the clock; do what it does. Keep going.",
    "The only way to do great work is to love what you do.",
    "The best way to predict the future is to create it.",
    "You miss 100% of the shots you don't take.",
    "Success usually comes to those who are too busy to be looking for it.",
    "It always seems impossible until it's done.",
    "Your time is limited, don't waste it living someone else's life."
]